### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.keyvault.models.Reason.account_name_invalid
  - azure.mgmt.keyvault.models.Reason.already_exists
  class: azure.mgmt.keyvault.models.Reason
  fullName: azure.mgmt.keyvault.models.Reason
  inheritance:
  - inheritance:
    - type: builtins.object
    type: builtins.str
  - inheritance:
    - type: builtins.object
    type: enum.Enum
  langs:
  - python
  module: azure.mgmt.keyvault.models
  name: Reason
  source:
    id: Reason
    path: azure-mgmt-keyvault\azure\mgmt\keyvault\models\key_vault_management_client_enums.py
    remote:
      branch: master
      path: azure-mgmt-keyvault\azure\mgmt\keyvault\models\key_vault_management_client_enums.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 109
  summary: 'An enumeration.



    '
  syntax: {}
  type: class
  uid: azure.mgmt.keyvault.models.Reason
- class: azure.mgmt.keyvault.models.Reason
  fullName: azure.mgmt.keyvault.models.Reason.account_name_invalid
  langs:
  - python
  module: azure.mgmt.keyvault.models
  name: account_name_invalid
  syntax:
    content: account_name_invalid = 'AccountNameInvalid'
  type: attribute
  uid: azure.mgmt.keyvault.models.Reason.account_name_invalid
- class: azure.mgmt.keyvault.models.Reason
  fullName: azure.mgmt.keyvault.models.Reason.already_exists
  langs:
  - python
  module: azure.mgmt.keyvault.models
  name: already_exists
  syntax:
    content: already_exists = 'AlreadyExists'
  type: attribute
  uid: azure.mgmt.keyvault.models.Reason.already_exists
references:
- fullName: azure.mgmt.keyvault.models.Reason.account_name_invalid
  isExternal: false
  name: account_name_invalid
  parent: azure.mgmt.keyvault.models.Reason
  uid: azure.mgmt.keyvault.models.Reason.account_name_invalid
- fullName: azure.mgmt.keyvault.models.Reason.already_exists
  isExternal: false
  name: already_exists
  parent: azure.mgmt.keyvault.models.Reason
  uid: azure.mgmt.keyvault.models.Reason.already_exists
